version: '3'
services:
  mongodb:
    container_name: hivent-groups
    image: mongo:4.0.3
    volumes:
      - mongodata:/data/hivent-groups
    ports:
      - "27018:27017"
volumes:
    mongodata: