version: '3'
services:
  mongodb:
    container_name: hivent-users
    image: mongo:4.0.3
    volumes:
      - mongodata:/data/hivent-users
    ports:
      - "27019:27017"
volumes:
    mongodata: